CREATE TABLE IF NOT EXISTS tilaukset (
  id SERIAL PRIMARY KEY,
  nimi VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  puhelin VARCHAR(50) NOT NULL,
  tuote VARCHAR(255) NOT NULL,
  maara INTEGER NOT NULL,
  pvm DATE NOT NULL,
  luotu_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);